name: php-fpm

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile.php-fpm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into tx docker registry
        run: echo "${{ secrets.DOCKERHUB_TX_TOKEN }}" | docker login  ccr.ccs.tencentyun.com -u ${{ secrets.DOCKERHUB_TX_USERNAME }} --password-stdin

      - name: docker push
        run: |
          docker build -t smallpond/php-fpm -f Dockerfile.php-fpm .
          docker push smallpond/php-fpm
